package tora.train.risk.clientserver.common;

/**
 * Type of message
 */
public enum MessageType {
	USER, GLOBAL, IDENTITY, READY, START, CONNECT, STOP, PLAYER_DISCONNECTED, NEW_PLAYER_CONNECTED,
    RESTRICT_CLIENT, RESTRICT_CONNECTION, YOUR_TURN, TRY_REINFORCE, REINFORCE_ACCEPTED, REINFORCE_DENIED, REINFORCE_END, START_TRANSFER, ONLINE_PLAYERS
}
