package tora.train.risk.clientserver.common;

/**
 * Type of message
 */
public enum MessageType {
	USER, GLOBAL, IDENTITY, READY, START, CONNECT, STOP, PLAYER_DISCONNECTED, NEW_PLAYER_CONNECTED,
    RESTRICT_CONNECTION, ONLINE_PLAYERS,

    NEW_ROUND, UNEXPECTED_COMMAND, YOUR_TURN, YOUR_REINFORCEMENTS, REINFORCE, REINFORCE_ACCEPTED,
    REINFORCE_REFUSED, REINFORCE_END
}
